TFMDIR = /usr/lib/tex/fonts

TFMS = min5.tfm   min6.tfm   min7.tfm   min8.tfm   min9.tfm   min10.tfm \
	  nmin5.tfm  nmin6.tfm  nmin7.tfm  nmin8.tfm  nmin9.tfm  nmin10.tfm \
	  goth5.tfm  goth6.tfm  goth7.tfm  goth8.tfm  goth9.tfm  goth10.tfm \
	  ngoth5.tfm ngoth6.tfm ngoth7.tfm ngoth8.tfm ngoth9.tfm ngoth10.tfm
all:;
	install -c -m 644 $(TFMS) $(TFMDIR)
