MACDIR = /usr/lib/tex/macros
MACROS = a4j.sty a5j.sty b4j.sty b5j.sty \
	jbk10.sty  jbk11.sty  jbk12.sty  jbook.sty \
	jrep10.sty jrep11.sty jrep12.sty jreport.sty \
	jart10.sty jart11.sty jart12.sty jarticle.sty \
	jlfonts.tex jlfonts2.tex kinsoku.tex kinsoku2.tex \
	jplain.tex jlplain.tex jsfonts.tex \
	jslides.sty jsplain.tex slitex.tex \
	jtwocolumn.sty landscape.sty ascmac.sty

all:;
	install -c -m 644 $(MACROS) $(MACDIR)
