#!/bin/sh
# Convert TeX to C.

cat ../lib/common.defines ../lib/texmf.defines ../lib/ptexmf.defines tex.p \
	| ../web2c/web2c -t -htexmf.h \
	| ../web2c/fixwrites \
	| ../web2c/regfix \
	| ../web2c/splitup

cat coerce.h coerce.add > xcoerce.h
mv xcoerce.h coerce.h
