#!/bin/sh

if [ -z "$1" ]; then
	echo "Usage: mkconf texmf.cnf"
	exit 2
fi

cnffile="$1"
if [ ! -f "$cnffile" ]; then
	echo "Error: $cnffile is not found"
	exit 2
fi

sed -e '/^% ptex, platex, platex209 macros paths./d
/^% pTeX./d
/^platex209_inputs *=/d
/^platex2e_inputs *=/d
/^ptex_inputs *=/d
/^TEXINPUTS.platex209 *=/d
/^TEXINPUTS.platex2e *=/d
/^TEXINPUTS.platex *=/d
/^TEXINPUTS.ptex *=/d
/^TEXINPUTS.iniptex *=/d
/^BIBINPUTS.jbibtex *=/d
/^BSTINPUTS.jbibtex *=/d' ${cnffile} | \
sed -e '/^TEXINPUTS.jadetex =/ a\
\
% pTeX.\
ptex_inputs = .;$TEXMF/{ptex,tex}/{plain,generic,}//\
platex209_inputs = .;$TEXMF/{ptex,tex}/{platex209,plain,platex,}//\
platex2e_inputs = .;$TEXMF/{ptex,tex}/{platex,latex,generic,}//\
TEXINPUTS.platex209 = $platex209_inputs\
TEXINPUTS.platex = $platex2e_inputs\
TEXINPUTS.ptex = $ptex_inputs\

/^% BibTeX bibliographies and style files./ a\
BIBINPUTS.jbibtex = .;$TEXMF/{jbibtex,bibtex}/bib//\
BSTINPUTS.jbibtex = .;$TEXMF/{jbibtex,bibtex}/bst//\
' | uniq

### EOT ###
