HDR	=arith.h binding.h box.h conv.h dvi.h dviclass.h dvicodes.h \
	error.h fio.h font.h gfclass.h gfcodes.h imPcodes.h imagen.h \
	io.h num.h postamble.h search.h str.h tfm.h types.h verser.h

goal:
	@echo Nothing to make here

$(HDR):
	co -q $@

hdr:	$(HDR)
	@echo Done
