#! /bin/csh -f
# A shell script to perform modifications on the texd.h file for ctex
# to make triptex instead of initex.
#
# To use it, say
#	ini_to_trip orig_texd.h trip_texd.ch
#
ed - $1 <<edscriptend
/undef	TRIP/
s/undef/define/p
/memmax/
s/[0-9][0-9]*/3999/p
/errorline/
s/[0-9][0-9]*/64/p
/halferrorline/
s/[0-9][0-9]*/32/p
/maxprintline/
s/[0-9][0-9]*/72/p
/maxinopen/
s/[0-9][0-9]*/6/p
/fontmax/
s/[0-9][0-9]*/75/p
/fontmemsize/
s/[0-9][0-9]*/20000/p
/maxstrings/
s/[0-9][0-9]*/3000/p
/stringvacancies/
s/[0-9][0-9]*/8000/p
/poolsize/
s/[0-9][0-9]*/32000/p
/savesize/
s/[0-9][0-9]*/600/p
/memtop/
s/[0-9][0-9]*/3999/p
w $2
edscriptend
